language changed with some field changed
pristren/dimetra-user pull request #46
Opened 2024-10-30 04:08 UTC by mrrafi5869

2024-10-30 12:05 UTC, mahmudulhaquequdrati requested changes

2024-10-30 12:05 UTC, mahmudulhaquequdrati commented on src/components/create-order-forms/billing-details/BillingDetails.jsx
> +                    <FormLabel className="font-normal">{t("name_institution")}</FormLabel>
aikane maybe area/lastname hobe,, deken toh er ager filed ta institute/firstname kina?

2024-10-30 17:03 UTC, kamruz-zzaman requested changes

2024-10-30 17:03 UTC, kamruz-zzaman commented on src/pages/order/all-orders/AllOrders.jsx
> +            {moment(date).format("dddd").slice(0, 3)})
```suggestion
            {moment(date).format("ddd")})
```

2024-10-30 17:35 UTC, mrrafi5869 commented on src/components/create-order-forms/preview-details/PreviewDetails.jsx
> +                        <Input disabled value={recurringData.free_dates_start_time} />
vai ekhaneto kono comment nai. ki bujaisen bujinai

2024-10-31 04:29 UTC, kamruz-zzaman approved these changes

2024-10-31 04:29 UTC, merged